// CSS for FoldKit Native: an app's stylesheet as written (FoldKit's examples
// use Tailwind 4), lowered to what happy-dom and the mirror can read.
//
//   bun run css            regenerate examples/*/styles.native.css
//   bun run css --check    fail if any generated file is stale (CI)
//
// happy-dom, the DOM FoldKit renders into here, ignores rules inside `@layer`,
// CSS nesting, `oklch()` and `color-mix()`, which is most of what Tailwind 4
// emits. So:
//
// 1. Tailwind compiles the classes the app uses, from its three parts imported
//    without cascade layers (Tailwind orders them theme, base, utilities, so
//    source order picks the same winner the layers would).
// 2. Lightning CSS lowers nesting and modern colours for old browsers.
// 3. A post-pass drops what happy-dom would get wrong: the `@supports` blocks
//    that put the modern colours back (happy-dom applies every `@supports`),
//    `@property` (ignored; Tailwind ships a plain fallback block), and that
//    block's `--x: initial` lines, which in a browser make `var(--x, fallback)`
//    use the fallback but in happy-dom substitute the word `initial`. It also
//    spells logical properties (`padding-inline`, Tailwind's `px-4`) as
//    physical ones, left to right: happy-dom ignores them, and Lightning CSS
//    leaves them alone when the value has a `var()`.
//
// Anything still left (calc(), color-mix() over variables) is evaluated in
// style.ts, after happy-dom has substituted the variables.

import { compile } from '@tailwindcss/node'
import { Scanner } from '@tailwindcss/oxide'
import { Features, transform } from 'lightningcss'
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { basename, dirname, join, resolve } from 'node:path'

/** Browsers old enough that Lightning CSS lowers everything happy-dom lacks. */
const TARGETS = { chrome: 80 << 16, safari: 13 << 16, firefox: 78 << 16 }

/** Compiles `styles.css` (Tailwind or plain CSS) to CSS the mirror can read. */
export const nativeCss = async (file: string): Promise<string> => {
  const dir = dirname(resolve(file))
  const source = readFileSync(file, 'utf8')
  const compiled = /@import\s+['"]tailwindcss['"]/.test(source) ? await tailwind(source, dir) : source
  const { code } = transform({
    filename: file,
    code: Buffer.from(compiled),
    targets: TARGETS,
    include: Features.Nesting | Features.Colors | Features.MediaQueries,
  })
  const lowered = dropBlocks(code.toString(), /^@(?:supports\s*\([^{]*(?:display-p3|lab\(|lch\(|color-mix)|property\b|layer\s+[\w-]+\s*;)/)
    .replace(/^\s*--[\w-]+:\s*initial;\n/gm, '')
    .replace(/^(\s*)([\w-]+):\s*([^;\n]+);$/gm, (line, indent: string, property: string, value: string) => {
      const physical = LOGICAL[property]
      if (physical === undefined) return line
      const [first, second = first] = splitValue(value)
      return physical.map((name, i) => `${indent}${name}: ${physical.length === 2 && i === 1 ? second : first};`).join('\n')
    })
    .replace(/^@layer [\w-]+ \{\n([\s\S]*?)^\}\n/gm, (_, body: string) => body.replace(/^ {2}/gm, ''))
  return `/* Generated by \`bun run css\` from ${basename(file)}. Don't edit. */\n${lowered}`
}

/** Logical properties → physical ones, for left-to-right text. */
const LOGICAL: Readonly<Record<string, ReadonlyArray<string>>> = {
  'padding-inline': ['padding-left', 'padding-right'], 'padding-block': ['padding-top', 'padding-bottom'],
  'padding-inline-start': ['padding-left'], 'padding-inline-end': ['padding-right'],
  'padding-block-start': ['padding-top'], 'padding-block-end': ['padding-bottom'],
  'margin-inline': ['margin-left', 'margin-right'], 'margin-block': ['margin-top', 'margin-bottom'],
  'margin-inline-start': ['margin-left'], 'margin-inline-end': ['margin-right'],
  'margin-block-start': ['margin-top'], 'margin-block-end': ['margin-bottom'],
  'inset-inline': ['left', 'right'], 'inset-block': ['top', 'bottom'],
  'inset-inline-start': ['left'], 'inset-inline-end': ['right'],
  'border-inline-width': ['border-left-width', 'border-right-width'],
  'border-block-width': ['border-top-width', 'border-bottom-width'],
  'border-start-start-radius': ['border-top-left-radius'], 'border-start-end-radius': ['border-top-right-radius'],
  'border-end-start-radius': ['border-bottom-left-radius'], 'border-end-end-radius': ['border-bottom-right-radius'],
  'inline-size': ['width'], 'block-size': ['height'],
  'min-inline-size': ['min-width'], 'min-block-size': ['min-height'],
  'max-inline-size': ['max-width'], 'max-block-size': ['max-height'],
}

/** Splits a value on spaces outside parentheses: `calc(a * 2) 4px` → two. */
const splitValue = (value: string) => {
  const parts: Array<string> = []
  let depth = 0
  let current = ''
  for (const char of value.trim()) {
    if (char === '(') depth++
    if (char === ')') depth--
    if (char === ' ' && depth === 0) {
      if (current !== '') parts.push(current)
      current = ''
    } else current += char
  }
  if (current !== '') parts.push(current)
  return parts
}

/** Removes every at-rule (with its block, or up to `;`) whose text matches. */
const dropBlocks = (css: string, header: RegExp) => {
  let out = ''
  let at = 0
  while (at < css.length) {
    const next = css.indexOf('@', at)
    if (next === -1) break
    if (!header.test(css.slice(next, next + 200))) {
      out += css.slice(at, next + 1)
      at = next + 1
      continue
    }
    out += css.slice(at, next)
    const semicolon = css.indexOf(';', next)
    const brace = css.indexOf('{', next)
    if (brace === -1 || (semicolon !== -1 && semicolon < brace)) {
      at = semicolon + 1
      continue
    }
    let depth = 0
    let end = brace
    for (; end < css.length; end++) {
      if (css[end] === '{') depth++
      else if (css[end] === '}' && --depth === 0) break
    }
    at = end + 1
  }
  return (out + css.slice(at)).replace(/\n{3,}/g, '\n\n')
}

/** `@import 'tailwindcss'` without cascade layers, so happy-dom sees the rules. */
const UNLAYERED = ['theme', 'preflight', 'utilities']
  .map(part => `@import '${Bun.resolveSync(`tailwindcss/${part}.css`, import.meta.dir)}';`)
  .join('\n')

const tailwind = async (source: string, base: string) => {
  const css = source.replace(/@import\s+['"]tailwindcss['"]\s*;/, UNLAYERED)
  const compiler = await compile(css, { base, onDependency: () => {} })
  const scanner = new Scanner({
    sources: [{ base, pattern: '**/*.ts', negated: false }, ...compiler.sources],
  })
  return compiler.build(scanner.scan())
}

if (import.meta.main) {
  const check = process.argv.includes('--check')
  const root = resolve(import.meta.dir, '../examples')
  let stale = 0
  for (const name of readdirSync(root).sort()) {
    const input = join(root, name, 'styles.css')
    if (!existsSync(input)) continue
    const output = join(root, name, 'styles.native.css')
    const css = await nativeCss(input)
    const current = existsSync(output) ? readFileSync(output, 'utf8') : ''
    if (css === current) continue
    if (check) {
      console.error(`stale: examples/${name}/styles.native.css (run \`bun run css\`)`)
      stale++
    } else {
      writeFileSync(output, css)
      console.log(`wrote examples/${name}/styles.native.css`)
    }
  }
  if (stale > 0) process.exit(1)
}
